README.md
**Description**
A link pointing to CERT-Polska/mquery was described as pointing to ursadb's repository. This small PR will fix it
=> Fix wrong link description

libursa/Utils.cpp
It compiled well because of invisible dependency from `json.h` but it should be there.
=> Add missing header

libursa/Query.cpp, src/Tests.cpp
Among others, we didn't test:
- wildcards in selects
- index from list construct
- reindex with construct
- topology, ping and status constructs
- taints and iterators
In other words, the tests were hopelessly outdated
=> Add missing parser tests

.github/workflows/build_deb.yml, .github/workflows/test_code.yml, CMakeLists.txt, Dockerfile, src/Client.cpp, src/Client.h
* Native ursadb client called `ursacli`
* Interactive mode / single command mode (supplied from argv)
* Progress reporting (additional thread which calls `status;` every second)
=> Implement ursacli, a native client

libursa/Command.h, libursa/Query.cpp, libursa/Query.h, libursa/QueryParser.cpp, src/Tests.cpp
It may be prone to mistakes, and there is no reason to copy queries
around. Especially with coming query graphs, this operation may
turn out to be very expensive.
=> Remove the copy constructor from Query class

src/Client.cpp, src/Client.h
* Implied non-interactive (quiet) mode when input is not a TTY (e.g. `echo 'status' | ursacli`)
* Additional `-j` command line switch to turn off output postprocessing in the client (and always get the raw JSON response from server)
* By default, `select` queries will return a simple list of files (newline separated text)
=> Adjustments in ursacli

CMakeLists.txt, libursa/CMakeLists.txt, libursa/Command.h, libursa/Core.cpp, libursa/Core.h, libursa/FeatureFlags.h, libursa/OnDiskDataset.cpp, libursa/OnDiskDataset.h, libursa/OnDiskIndex.cpp, libursa/OnDiskIndex.h, libursa/Query.cpp, libursa/Query.h, libursa/QueryGraph.cpp, libursa/QueryGraph.h, libursa/QueryParser.cpp, libursa/QueryParser.h, libursa/QueryResult.cpp, libursa/QueryResult.h, libursa/Utils.cpp, libursa/Utils.h, src/Daemon.cpp
This is the first step to QueryGraphs on production. There are no precise
measurements yet, but it gives us power to execute queries that would be
completely impossible to optimize before. For example:
```
ursadb> select into iterator {1? 2? 3? 4? 5? 6? 7? 8?};
[2020-04-14 23:17:11.177] [info] {
"result": {
"file_count": 5,
"iterator": "1c36d313",
"mode": "iterator"
},
"type": "select"
}
```
There are only 5 files (out of 50k) in the result, a reduction factor of
1/10k. Not bad. The performance is... better than expected (there are
basically no optimisations yet), but needs testing on bigger datasets.
The most important caveat is that this is not stable yet. It's relatively
easy to kill the DB using a query like:
```
select {?? ?? ?? ??};
```
We need a way to prune query graphs during …
=> Add a new experimental feature: QueryGraphs

libursa/QueryGraph.cpp, libursa/QueryGraph.h
This will make future graph operation much easier, by decoupling graph
traversal from actual operations
=> Implement a query graph inorder visitor

libursa/OnDiskIndex.cpp, libursa/QString.cpp, libursa/QString.h
Constants in OnDiskIndex.cpp explain it all:
```
// Maximum number of possible values for the edge to be considered.
// If token has more than MAX_EDGE possible values, it will never start
// or end a subgraph. This is to avoid starting a subquery with `??`.
constexpr uint32_t MAX_EDGE = 16;
// Maximum number of possible values for ngram to be considered. If ngram
// has more than MAX_NGRAM possible values, it won't be included in the
// graph and the graph will be split into one or more subgraphs.
constexpr uint32_t MAX_NGRAM = 256 * 256;
```
Oh the one hand, this is far from perfect. For example there is a **huge**
performance difference between:
```
BB CC ?? DD ?? EE FF
```
And
```
A? B? C? ?? D? E? F?
```
The first one will execute in miliseconds, while the second one will take a
long …
=> Implement a naive graph pruning algorithm

libursa/OnDiskIndex.cpp, libursa/QString.cpp, libursa/QString.h, libursa/Query.cpp, libursa/QueryParser.cpp, src/Tests.cpp
For example {aa bb (11 | 22) cc dd}
fixes #65
=> Implement alternatives in the query syntax

libursa/DatabaseHandle.cpp, libursa/ZHelpers.cpp, libursa/ZHelpers.h, src/Client.cpp, src/NetworkService.cpp
* Remove `s_send_val` and replace with uniform interface - `s_send` / `s_recv`
* Introduce `s_send/recv_raw` for raw access to socket - generally shouldn't be used for in code
* Introduce helper function `s_send/recv_padding` for handling padding messages
* Allow only simple types to be sent over the socket (with the possibility to implement serialization of more types)
* Make s_send/s_recv interface compatible with Google style guide (pointer instead of reference)
=> Refactor networking

libursa/Command.h, libursa/DatabaseSnapshot.cpp, libursa/DatabaseSnapshot.h, libursa/QueryParser.cpp, src/Benchmark.cpp, src/Daemon.cpp, src/Tests.cpp
Sometimes we want to index files *without* a safety belt that index
provides. One of the reasons ot do this is when the list of files doesn't
fit into RAM (or storing it there is too memory expensive to be useful).
In this case, curated list of files can be provided to the db, and `nocheck`
modifier tells the db that the file list is guaranteed to be unique.
=> Add a nocheck modifier for index commend

libursa/FlatIndexBuilder.cpp, libursa/FlatIndexBuilder.h, src/Benchmark.cpp
Saving the index builder is the slowest part of the whole process.
This change makes it much faster.
The slowest part of the save was std::sort on the ngrams. In this change I
rewrite the std::sort to a handwritten radixsort. This accounts for most
of the speedup.
Before (in ms):
1 - 2: 9611
1 - 2: 10055
1 - 2: 9555
After (in ms):
1 - 2: 1871
1 - 2: 1907
1 - 2: 1731
Another thing that was optimised is the process of saving data to disk. It
used to use ofstream::put, I've rewritten it to use a temporary std vector
and only spill the data at the end.
Before (in ms):
3 - 4: 1158
3 - 4: 1136
3 - 4: 1056
After (in ms):
3 - 4: 472
3 - 4: 520
3 - 4: 487
In total, this improves the index dump time significantly:
Before (in ms):
index(100, 1000000): 11797
index(100, 1000000): 12222
index(100, …
=> Optimise the FlatIndexBuilder save process.

libursa/CMakeLists.txt, libursa/DatabaseUpgrader.cpp, libursa/DatabaseUpgrader.h, src/Daemon.cpp
I'll quote my comment:
Historically, ursadb database files were very stable. But we don't want
and don't have to guarantee their exact structure - especially since
they're JSON and can be easily extended with new data. This function will
read the db files from disk, upgrade them if necessary, and return.
=> Add a way to migrate database storage versions

libursa/OnDiskIndex.cpp, libursa/QString.h, libursa/QueryGraph.cpp, libursa/QueryGraph.h, libursa/QueryResult.h, src/Tests.cpp
Right now this is only used to slightly refactor graph parsing code. But
don't be mistaken, soon this will allow for huge improvements, because
it opens a possibility of merging querygraphs (without quadratic node cost).
It manifests itself in an ever so slight optimisation that can be seen here:
```
select {?1 ?2 ?3 ?4 ?5 ?6};                      average    146.137 files: 513
select {61 62 63} & {?1 ?2 ?3 ?4 ?5 ?6};         average    141.116 files: 60
select {61 62 63 ?? ?? ?? ?1 ?2 ?3 ?4 ?5 ?6 ?8}; average     21.913 files: 13
select {?1 ?2 ?3 ?4 ?5 ?6} & {61 62 63};         average    139.955 files: 60
select {?1 ?2 ?3 ?4 ?5 ?6 ?? ?? ?? 61 62 63};    average    136.847 files: 13
```
The middle operation is visibly faster than the other ones (even though
they're all equivalent except …
=> Add epsilon nodes to querygraphs and use them

libursa/CMakeLists.txt, libursa/Command.h, libursa/Database.cpp, libursa/Database.h, libursa/DatabaseConfig.cpp, libursa/DatabaseConfig.h, libursa/DatabaseSnapshot.cpp, libursa/DatabaseSnapshot.h, libursa/QueryParser.cpp, libursa/Responses.cpp, libursa/Responses.h, libursa/Task.cpp, libursa/Task.h, src/Daemon.cpp, teste2e/test_config.py
This adds two commands: `config get` and `config set`:
```
config get;  # gets complete config
config get "key";  # gets key "key";
config get "key1" "key2";  # gets keys "key1" and "key2"
```
```
config set "key" 123  # sets key value
```
Currently recognised keys are `query_max_edge` and `query_max_edge` - but
they're not actually supported (i.e. the value is ignored).
=> Add two config related commands - config get and set

libursa/DatabaseSnapshot.cpp, libursa/DatabaseSnapshot.h, libursa/OnDiskDataset.cpp, libursa/OnDiskDataset.h
Right now we don't care how many datasets we want to compact at once.
Ursadb believes it can handle it. Ursadb believes in itself very hard,
it doesn't change the fact that with few hundred datasets at once
compacting gets pretty hard.
This change ensures that the database won't try to compact more than
a hardcoded number of datasets, and also it won't try to compact
more than one set of datasets (heh) at once. Finally, it tries to check
for the possibility that datasets are locked, and ignore them in this
case.
=> Rework compacting. Respect RAM more.

libursa/DatasetBuilder.cpp, libursa/OnDiskDataset.cpp, libursa/OnDiskFileIndex.cpp, libursa/OnDiskFileIndex.h, libursa/Utils.cpp, libursa/Utils.h
Right now namecache files are regenerated every time. This slows down the startup unjustly. We should generate them, and update dataset with that file instead.
resolve #98
=> Save namecache files

libursa/Command.h, libursa/QueryParser.cpp, src/Daemon.cpp, src/Tests.cpp, teste2e/test_core.py, teste2e/test_stability_merge.py
Ok, why would anyone need this. This is intended to decrease speed to first
result in mquery. Instead of doing one big query, mquery will query datasets
one by one.
Now I can hear you asking: WHY would the logic for this be in mquery? Isn't
async querying a pretty generic use-case? So I agree, but implementing this
in mquery opens a can of worms that I'm not ready to handle, for example:
- Database can change during the query (solution: persistent snapshots?)
- Database can't know when it's OK to stop streaming (for example, user
cancelled a query, or yara can't catch up).
- It makes database performance even more opaque - is it idle? Or are there
tasks busy in the background?
Because of this, I think that querying DSets one by one is a good solution for
now. The proper solution would be …
=> Another specialisation for select - select with datasets.

.github/workflows/test_experiments.yml, libursa/OnDiskIndex.cpp, libursa/QString.h, libursa/QueryGraph.cpp, libursa/QueryGraph.h, libursa/Utils.cpp, libursa/Utils.h, src/Tests.cpp, teste2e/test_core.py, teste2e/test_format_upgrades.py, teste2e/test_iterators.py, teste2e/test_sanity.py, teste2e/test_stability_merge.py
- no arbitrary restriction on wide8 queries
- actually unit test them (regression found)
- make query graph expansion faster (validate grams before)
With this change they will be *basically* ready to deploy as a default
configuration. Maybe few more tests and I think we can :shipit:.
=> Make query graphs production ready

libursa/DatabaseSnapshot.cpp, libursa/DatabaseSnapshot.h, libursa/OnDiskDataset.cpp, libursa/OnDiskDataset.h, libursa/QueryResult.cpp, libursa/QueryResult.h, libursa/Responses.cpp, libursa/Responses.h, src/Daemon.cpp, src/Tests.cpp
`select` queries will return some useful metrics (for example,
number of files read and written).
```
ursadb> select {a? b? c? d? ee ff};
{
"counters": {
"and": {
"count": 419339,
"in_files": 14714965,
"milliseconds": 73,
"out_files": 44160
},
"or": {
"count": 419424,
"in_files": 368944,
"milliseconds": 17,
"out_files": 367750
},
"read": {
"count": 838758,
"in_files": 0,
"milliseconds": 0,
"out_files": 14672000
}
},
"result": {
"files": [
"/home/msm/Projects/mquery/samples/f4b3d12706927fc74767b1cfac194801"
],
"mode": "raw"
},
"type": "select"
}
```
(milliseconds in the `read` section are of course not valid).
=> Add performance counters to the response.

libursa/QueryGraph.cpp
When there is only single predecessor, do a simple AND without ANDing with a temporary and ORing with the empty result.
Before:
```
"counters": {
"and": {
"count": 33,
"in_files": 432,
"milliseconds": 0,
"out_files": 4
},
"or": {
"count": 30,
"in_files": 4,
"milliseconds": 0,
"out_files": 4
},
"read": {
"count": 60,
"in_files": 0,
"milliseconds": 0,
"out_files": 428
}
},
```
After:
```
"counters": {
"and": {
"count": 33,
"in_files": 432,
"milliseconds": 0,
"out_files": 4
},
"or": {
"count": 8,
"in_files": 0,
"milliseconds": 0,
"out_files": 0
},
"read": {
"count": 38,
"in_files": 0,
"milliseconds": 0,
"out_files": 428
}
},
```
=> Don't do unnecessary ORs in query graph selects.

libursa/QueryGraph.cpp, libursa/QueryResult.h
Before:
```
"counters": {
"and": {
"count": 217,
"in_files": 209,
"milliseconds": 0,
"out_files": 0
},
"or": {
"count": 8,
"in_files": 0,
"milliseconds": 0,
"out_files": 0
},
"read": {
"count": 222,
"in_files": 0,
"milliseconds": 0,
"out_files": 209
}
},
```
After:
```
"counters": {
"and": {
"count": 11,
"in_files": 0,
"milliseconds": 0,
"out_files": 0
},
"or": {
"count": 0,
"in_files": 0,
"milliseconds": 0,
"out_files": 0
},
"read": {
"count": 8,
"in_files": 0,
"milliseconds": 0,
"out_files": 0
}
},
```
Probably won't matter much on real-world queries and big indexes, though :thinking:
=> Don't do unnecessary index reads for empty ANDs.

libursa/QueryGraph.cpp, libursa/QueryResult.cpp, libursa/QueryResult.h
It turns out, that not every graph is a tree. So we can't really recursively
accumulate results, because we'll end up with huge incorrect numbres.
=> Fix performance counters for query graphs

libursa/QueryGraph.cpp
This could produce invalid results on some complex-but-useful queries, like:
select into iterator ((({(61|41) (62|42) (63|43) (64|44)} | {(61|41) 00 (62|42) 00 (63|43) 00 (64|44) 00})))
(in this case, even segfault because sources were not cleaned properly).
=> Fix failed optimisation for OR on empty graphs.

libursa/OnDiskIterator.cpp, teste2e/test_select.py, teste2e/util.py
Due to improper use of file read functions, iterator select didn't
work properly when filename contained spaces.
=> Fix iterator selects for filenames with spaces

libursa/Daemon.cpp, libursa/DatabaseSnapshot.h, teste2e/test_indexing.py
`index from list "/tmp/files.txt"` assumes all the paths are files, and this is not the expected behaviour. It was changed during the refactoring and not noticed until now.
=> Fix index from list command

libursa/DatabaseSnapshot.cpp, libursa/OnDiskDataset.cpp, libursa/OnDiskDataset.h, libursa/OnDiskIndex.h, libursa/Query.cpp, libursa/Query.h, src/Tests.cpp, teste2e/test_select.py, teste2e/util.py
Due to a refactoring earlier (probably), we started returning
many more results than we should. This commit should fix this,
without affecting performance negatively.
=> Fix performance and accuracy for wide ascii strings

libursa/QueryResult.cpp, teste2e/test_select.py
Could be reproduced with, for example
select min 2 of ("cat", "dog")
is_everything flag in QueryResult::do_min_of_real was never cleared
=> Fix regression when reducing minof queries to AND

.github/workflows/test_code.yml, CMakeLists.txt, libursa/Daemon.cpp, libursa/Daemon.h, src/Compact.cpp, src/Index.cpp
We are using ursadb to index a large number of malware samples from a live feed (you can probably imagine which one). Today, we handle the volume by partitioning and horizontally scaling by date. A beefy index system creates the databases and then we re-attach the volumes to lightweight daemons hosted by a cloud provider.
In the above setup, the "index" and "compact" steps are discrete and synchronous; spawning long-running ursadb server instances (via docker) to handle a single index and compact cycle added unwanted complexity (e.g. server dies, pod dies, doesn't restart, zmq gets confused, ...). Surely we could add more effort around the deployment, but is simpler to reason about a single process that does a single step. Therefore...
This PR introduces standalone binaries for indexing …
=> add standalone indexer and compaction binaries

.gitmodules, extern/CMakeLists.txt, libursa/CMakeLists.txt
This PR may be a matter of style: it introduces submodules for libzmq and cppzmq and statically links these libraries to libursa. 
Motivation: I had a little trouble copying and executing ursa binaries on our cloud provider, and while this could probably be solved by fixing the library paths on the remote side, I went with the static-linking approach.
=> static linking and submodules

README.md
Suggestion:
Remove emails, as they get outdated quickly. Github is the best way to discuss the project (in case direct contact is necessary, it's not hard to extract email information from commits, for example).
Fixes #177
=> Remove direct email contacts from Github.

.github/workflows/push_hub.yml, Dockerfile
First of all, thanks guys for your work on the UrsaDB. We're currently implementing it in our own projects to speed up our yara-searches. 
However, we're aiming to use your docker images for running UrsaDB. Delving into this, we've seen that the Dockerhub UrsaDB is quite outdated (build may 2020) and does not follow some security considerations with regards to Docker images. Due to the fact mine organization is quite security minded I've added some additions.
1. Add automatic docker image rebuilds every first day of the month (04:24). This ensures that the image is build on the latest Debian image with the latest security patches. 
2. Ensure the UrsaDB process is run under a different user than root, (ursa 1000:1000)
3. Make building it a little faster by using `make` with multicore …
=> Docker improvements

libursa/MemMap.h
This one is pretty critical bugfix and will probably hasten a new release.
Size method used to return a reference to a local variable. This is UB and it only works by accident. Turns out it doesn't work anymore with clang on architectures other than x86.
CC @chivay @patryk4815 and thanks for the help debugging.
=> Fix Undefined Behaviour when getting a memory map size

.github/workflows/test_code.yml
I don't have time nor sanity to configure it properly.
There are dozens of errors in the modified source files, most of which are like "ds name is too short" or "(unused function) is too complex" or "parameters are easily swappable".
I may even agree with some of them, but they're not important enough to fix right now.
=> Disable clang-tidy, which become very noisy.

.github/workflows/test_code.yml, libursa/DatabaseSnapshot.cpp, libursa/DatabaseSnapshot.h, libursa/OnDiskDataset.cpp, libursa/OnDiskIndex.cpp, libursa/OnDiskIndex.h, libursa/QString.h, libursa/Query.cpp, libursa/Query.h, libursa/Utils.cpp, libursa/Utils.h, src/Benchmark.cpp, teste2e/test_indexing.py, teste2e/test_select.py
While "Query Plans" sound like an advanced feature, this is actually an regression from QueryGraphs. Even more - after this PR query graphs will be unused and we could remove them in principle.
This PR reduces the number of reads between 10% and 300%. As seen on this screenshot (ignore time in `ms`, it's related to disk load and cache contents at the benchmark moment - read count is what matters):
Since read is the most time consuming part of ursadb work, especially on HDD, this may speed up the database significantly.
In this PR I rewrite the matching algorithm to use a minimal covering set of necessary ngrams. For example, to match:
```
abcde?ghi
```
(where ? in an unknown/missing character), we will check the following ngrams (assuming all indexes are available):
```
abcd
bcde
ghi
``` …
=> Performance improvement 1: queryplans

libursa/OnDiskDataset.cpp, libursa/Query.cpp, libursa/Query.h, libursa/QueryCounters.cpp, libursa/QueryCounters.h
Fixes #198.
This code adds tracking of unique ngram reads. This is the most important performance metrics on slow disks, so it'll be quite useful for future performance improvements.
Implementation-wise it's quite simple, the only nontrivial part is that I had to add operator< for PrimitiveQuery to put it into set::set.
=> Implement counter of unique ngram reads

libursa/Database.cpp
Self-explanatory. The code is careful to handle 64bit values properly and not assign them to 32bit somewhere, but in this case they're clamped to 32bit (signed) at the very beginning.
This affects reads from iterators that have more than 2GB of filenames stored.
=> Fix a bug that manifested with 2gb+ iterators (during indexing)

libursa/Database.cpp, libursa/Database.h, libursa/DatabaseConfig.h, libursa/DatabaseUpgrader.cpp, libursa/OnDiskIterator.cpp, libursa/OnDiskIterator.h, libursa/Version.h.in, teste2e/test_format_upgrades.py
Clean up old iterators from disk after some time (by default: one day).
**Warning** - this will remove all existing iterators when the database version is updated. This shouldn't be a huge problem, but it will break any long running queries using iterators (for example, from mquery). That's because default "age" of iterator is very old.
There are two ways to fix this:
- Use current time as a default age of iterator - wouldn't work, because iterators that are not read won't ever get updated time and be GCed. And these are precisely iterators we want to remove!
- By default disable iterator GC. But I want GC to be enabled by default! I don't want to ship database broken by default and require users to change the config.
There is one workaround for people that really care - they can manually …
=> Implement GC for iterators

CMakeLists.txt, RELEASES.md
PR that bumps the source code version. No real new features (iterator GC is more a bugfix for mquery than real feature), but a few important bugfixes.
=> Draft release v1.5.1

libursa/CMakeLists.txt, libursa/Query.cpp, libursa/Query.h, libursa/Version.h.in
Instead of having a dedicated query type to AND of tokens, we can just create a query type for tokens and use AND query type with them. This makes optimization easier later.
This PR also changes the way build versions work (the current method with git revision parsing was too brittle, and didn't work for me).
=> Refactor primitive queries into AND of atoms

libursa/OnDiskDataset.cpp, libursa/Query.cpp, libursa/Version.h.in, src/NetworkService.cpp
This makes understanding future optimizations easier.
=> Add debug logs, including query plans

libursa/CMakeLists.txt, libursa/OnDiskDataset.cpp, libursa/Query.cpp, libursa/Query.h, libursa/QueryOptimizer.cpp, libursa/QueryOptimizer.h, libursa/Version.h.in
This is currently useless, but this version will be used as base for future optimizations.
=> Create the optimizer framework

libursa/QueryOptimizer.cpp, libursa/Version.h.in
```
// This optimization inlines eliglible suboperations:
// AND(AND(a, b), AND(c, d), e) --> AND(a, b, c, d, e)
// OR(OR(a, b), OR(c, d), e) --> OR(a, b, c, d, e)
```
=> opt2: inline_suboperations

libursa/Query.cpp, libursa/Query.h, libursa/QueryOptimizer.cpp, libursa/Version.h.in
```
// This optimization gets rid of duplicated primitive queries.
// AND(a, a, a, a, b, b) == AND(a, b)
// This also applies to OR(), but it'll happen very rarely.
```
=> opt3: deduplicate_primitives

libursa/QueryOptimizer.cpp, libursa/Version.h.in
```
// Propagate 'everything' results through the query. For example,
// if we know that C is everything, we immediately know OR(a, b, C)
// OR(AND(), b, c) --> AND()
// MIN 3 OF (AND(), b, c, d) --> MIN 2 OF (b, c, d)
```
=> opt5: propagate_degenerate_queries

libursa/QueryOptimizer.cpp, libursa/Version.h.in
```
// Order the subqueries to maximize the chance of early exit.
// This is done after all other optimizations, and there's no point of
// running this in a loop.
```
=> opt6: reorder_subqueries

libursa/OnDiskDataset.cpp, libursa/OnDiskIndex.cpp, libursa/OnDiskIndex.h, libursa/Query.cpp, libursa/Query.h, libursa/RawFile.cpp, libursa/RawFile.h, libursa/Version.h.in
```
// Prefetch the next `howmany` ngrams.
// This doesn't recurse into other queries. It's not a big problem,
// because all primitives that we can fetch are in long AND sequences.
// But in the future we may consider improving this.
```
=> opt7: prefetching

libursa/OnDiskDataset.cpp, libursa/OnDiskIndex.cpp, libursa/OnDiskIndex.h, libursa/Query.cpp, libursa/QueryOptimizer.cpp, libursa/QueryResult.cpp, libursa/QueryResult.h, libursa/SortedRun.cpp, libursa/SortedRun.h, libursa/Utils.h, libursa/Version.h.in, src/Tests.cpp
After reading run from an index file, don't decompress it immediately. Instead, parse the compressed representation on the go, to reduce a memory pressure.
=> opt8: keep runs in compressed form

libursa/SortedRun.cpp, libursa/SortedRun.h, libursa/Version.h.in
Optimize ANDing uncompressed and compressed sorted runs:
```
// Performance critical method. As of the current version, in some tests,
// more than half of the time is spent ANDing decompressed and compressed runs.
// We expect the compressed set to be large, and sequence to be short.
```
Unfortunately, the fast-case code is significantly ugly, but the speedup is worth it (AND gets almost 200% faster, and this transfers to almost 10% faster total time, depending on the workload [1]).
On the other hand, experiments with AVX2 were slightly disappointing - they give another 5% performance, but are even uglier and also make the code dependent on the CPU flags (so we probably need a fallback anyway). Most people on the internet manage to get a larger speedup from AVX, so this may be a skill …
=> opt9: batch vle processing

CMakeLists.txt, RELEASES.md
This release consists almost exclusively of performance improvements. Query speed is reduced by over 50% in the tested workloads.
Features:
- Add a verbose mode (-v) that also prints debug logs (#218) 
Performance:
- Refactor  (#218) 
- Add debug logs, including query plans (#218)
- opt1: Flatten trivial operations (#220)
- opt2: Inline suboperations (#221)
- opt3: Deduplicate primitives (#222)
- opt4: Simplify minof in some cases (#223)
- opt5: Propagate degenerate queries (#224)
- opt6: Reorder subqueries more optimally (#225)
- opt7: Prefetch disk reads (#226)
- opt8: Keep runs in compressed form for longer (#227)
Correctness:
Refactoring and maintenance:
- Create a simple framework for query optimizations (#217) 
---
Tests were performed on a dataset consisting of 9416097 files (over …
=> Release v1.5.2
