CERT-Polska/ursadb

- CMakeLists.txt
- Command.h
- Daemon.cpp
- Database.cpp
- Database.h
- DatabaseHandle.cpp
- DatabaseHandle.h
- DatabaseSnapshot.cpp
- DatabaseSnapshot.h
- Indexer.cpp
- NetworkService.cpp
- NetworkService.h
- OnDiskDataset.cpp
- OnDiskDataset.h
- OnDiskIterator.cpp
- OnDiskIterator.h
- QueryParser.cpp
- Responses.cpp
- Responses.h
- ResultWriter.h
- Task.cpp
- Task.h
- Tests.cpp
- Version.h
Two new database commands:
```
select into iterator "query";
iterator "name" pop 30;
```
> Implement streaming iterators

- deploy/k8s/ursadb.yml
Doing this on github feels weird.
> Update deploy schema for our internal instance

- .github/workflows/test_code.yml
Can be merged after #37 - fixing dockerfile
> Test Docker build

- src/NetworkService.cpp
> Fix threading

- .github/workflows/build_deb.yml
- CMakeLists.txt
- README.md
* Debian package building with `cpack` command
* More detailed build instructions in README.md
* Github Action to draft a new release once a tag with name `v*` is created
> Add CPack to CMakeLists, fix build README

- .github/workflows/build_deb.yml
* Always try to build package, release it only if a new tag is created
* Checkout submodules when checking out the repo
* Test package installation after build
> Fix package build CI

- RELEASES.md
All the cool projects in the blocks have release notes. I want in!
> Add missing notes for the v1.3.0 release

- libursa/CMakeLists.txt
- libursa/Core.cpp
- libursa/Core.h
- libursa/QueryGraph.cpp
- libursa/QueryGraph.h
This is not currently used during querying, but the core operations are
already implemented and we're almost ready to get to the cool stuff.
> Implement QueryGraphs for future optimisations

- Dockerfile
- README.md
- libursa/CMakeLists.txt
- libursa/Utils.cpp
- libursa/Utils.h
- libursa/Version.h.in
- src/Daemon.cpp
> Add commit hash to libursa

- .github/workflows/coverity-scan.yml
Build master branch and send to Coverity
> Add coverity scan

- libursa/CMakeLists.txt
- libursa/Command.h
- libursa/Core.cpp
- libursa/Core.h
- libursa/OnDiskIndex.cpp
- libursa/OnDiskIndex.h
- libursa/QString.cpp
- libursa/QString.h
- libursa/Query.cpp
- libursa/Query.h
- libursa/QueryGraph.h
- libursa/QueryParser.cpp
- libursa/Utils.cpp
- libursa/Utils.h
- src/Tests.cpp
Change the way qstring works - but also keep legacy API for clients
that don't use EXPERIMENTAL_GRAPH_QUERY mode yet.
> Refactor qstring, and prepare for a new approach

- src/Tests.cpp
Index testing was ugly, modernise it a bit
> Refactor tests, round 1

- .github/workflows/build_deb.yml
- libursa/ZHelpers.cpp
- libursa/ZHelpers.h
- src/Client.cpp
- src/Client.h
Reworked cli a bit. Fixed 100% CPU usage bug.
> Multiple ursacli fixes

- libursa/Database.cpp
- libursa/DatabaseSnapshot.cpp
- teste2e/test_core.py
- teste2e/test_iterators.py
- teste2e/test_reindex.py
- teste2e/util.py
Also add a lot of tests to make sure this does not happen again
> Fix reindexing, to keep taints in new datasets.

- libursa/OnDiskIndex.cpp
- libursa/OnDiskIndex.h
- libursa/RawFile.cpp
- libursa/RawFile.h
- libursa/Utils.cpp
- libursa/Utils.h
This makes the algorithm much faster on HDDs.
> Rewrite merge algorithm to utilise more batching

- libursa/Database.cpp
- libursa/DatabaseSnapshot.cpp
- libursa/DatabaseSnapshot.h
- libursa/Responses.cpp
- libursa/Responses.h
- libursa/Task.h
- teste2e/test_core.py
- teste2e/test_stability_status.py
Right now there are race conditions in the `status` command. Remove them.
> Fix task safety issues

- libursa/DatabaseSnapshot.cpp
- libursa/OnDiskDataset.cpp
- libursa/OnDiskDataset.h
- libursa/OnDiskIndex.cpp
- libursa/OnDiskIndex.h
- libursa/Query.cpp
- libursa/Query.h
- libursa/QueryGraph.cpp
- libursa/QueryGraph.h
- libursa/QueryResult.cpp
- libursa/QueryResult.h
- src/Tests.cpp
Gotta go fast. We're still not doing all the optimisations that we technically
could with this representation. There's even a small regression, because
we don't try to short circuit min...of queries.
> Merge all queries into one large graph before executing the query.

- libursa/Command.h
- libursa/Database.cpp
- libursa/DatabaseSnapshot.cpp
- libursa/QueryParser.cpp
- src/Daemon.cpp
> Drop dataset command

- libursa/Utils.cpp
- libursa/Utils.h
Not that indexing such files is a good idea anyway...
> Fix for large file handling

- CMakeLists.txt
- libursa/Database.cpp
- libursa/Database.h
- libursa/OnDiskDataset.h
- libursa/OnDiskIterator.cpp
- libursa/OnDiskIterator.h
- src/Environment.cpp
- src/Environment.h
- src/NetworkService.cpp
- src/Trim.cpp
It was not maintained for a long time, and looks like it didn't take iterators
into account.
TODO: we probably need to test it to prevent regressions...
> Fix trim command

- .gitignore
- libursa/BitmapIndexBuilder.cpp
- libursa/Core.cpp
- libursa/Daemon.cpp
- libursa/Database.cpp
- libursa/Database.h
- libursa/DatabaseSnapshot.cpp
- libursa/DatabaseSnapshot.h
- libursa/DatabaseUpgrader.cpp
- libursa/FlatIndexBuilder.cpp
- libursa/MemMap.cpp
- libursa/OnDiskDataset.h
- libursa/QString.h
- libursa/Query.cpp
- libursa/Query.h
- libursa/QueryGraph.cpp
- libursa/QueryGraph.h
- libursa/QueryParser.cpp
- libursa/QueryResult.h
- libursa/RawFile.cpp
- libursa/Responses.h
- libursa/Task.h
- libursa/Utils.cpp
- libursa/Utils.h
- libursa/ZHelpers.h
- src/Client.cpp
- src/NetworkService.cpp
- src/Tests.cpp
- src/Trim.cpp
Our biggest problem is return after else, apparantly.
> Apply fixes suggested by clang-tidy `readability-*`

- .github/workflows/test_code.yml
- src/Benchmark.cpp
> Fix CI pipeline

- src/Client.cpp
Remove a lock left in the quiet mode by mistake.
TODO: maybe spdlog should just be quiet in this mode :thinking:
> Make ursadcli quiet when asked

- libursa/QueryGraph.h
- libursa/ZHelpers.cpp
- libursa/ZHelpers.h
- src/Client.cpp
- src/NetworkService.cpp
Basically what the title says.
This will help us debug future ZMQ protocol errors.
closes #66.
> Add a simple traceback to every zeromq call

- .github/workflows/push_hub.yml
Building and storing the image on docker hub will allow us to unlink ursadb submodule from mquery
> Build and publish docker images

- CMakeLists.txt
- RELEASES.md
- docs/install.md
- docs/new_release.md
- docs/start.md
PR that bumps the source code version. I've also added instruction for future maintainers (including me) so I won't forget the steps again it in the future.
Fixes #173
> Draft release v1.5.0

- libursa/DatasetBuilder.cpp
- libursa/DatasetBuilder.h
- libursa/MemMap.cpp
- libursa/MemMap.h
Remove GNU-specific extensions (as a part of effort to make the code darvin-compatible).
> Remove gnuisms

- extern/catch/Catch.h
We use a quite old version of catch. Bump it.
> Bump catch v2.2.2 -> v2.13.10 (4.5 years difference!)

- README.md
Fix documentation URL in the readme.
> Fix docs url (it randomly changed at some point)

- libursa/QueryOptimizer.cpp
- libursa/Version.h.in
```
// This optimization simplifies trivial (one operant) operations:
// AND(x) --> x
// OR(x)  --> x
```
> opt1: flatten_trivial_operations
